services:
  database:
    image: postgres
    hostname: tmdb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
    networks:
      - zadataknet

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 6060:8080
    networks:
      - zadataknet

  zadatak:
    build: .
    restart: always
    depends_on:
      - datebase
    networks:
      - zadataknet
    
networks:
  zadataknet:
